
openapi: "3.0.0"

info:
  title: "E-commerce REST API"
  version: "1.0.0"
  description: "Generic endpoints for an e-commerce REST API. The 'Could not render n, see the console.' errors are a bug in the Swagger platform, afaik."

servers:
  - url: http://localhost:4000
    description: Local dev server. No SSL. You probably can't see this.
  - url: https://e-commerce-rest-api-v2.herokuapp.com
    description: Production server. Should provide SSL.

tags:
- name: "cart"
  description: "User cart endpoint"
- name: "login"
  description: "Login endpoint"
- name: "order"
  description: "Order endpoint"
- name: "product"
  description: "Product endpoint"
- name: "product-category"
  description: "Product category endpoint"
- name: "register"
  description: "Register endpoint"
- name: "user"
  description: "User endpoint"
- name: "address"
  description: "Address endpoint"
- name: "payment"
  description: "Payment information. Sensitive data is encryped upon insert"
- name: 'payment-type'
  description: "Payment types"

paths:
  /api/v1/cart:
    get:
      tags: 
      - "cart"
      summary: "Get all carts"
      description: "Get all carts without an order date"
      parameters: []
      responses:
        $ref: '#/components/responses/200-204-400'
    post:
      tags: 
      - "cart"
      summary: "Add item to a cart"
      requestBody:
        $ref: '#/components/requestBodies/CartItem'
      responses:
        $ref: '#/components/responses/200-400'
    put:
      tags: 
      - "cart"
      summary: "Update a cart item"
      description: "Update a cart item's quantity and line item price"
      requestBody:
        $ref: '#/components/requestBodies/CartItem'
      responses:
        $ref: '#/components/responses/200-204-400'
    delete:
      tags: 
      - "cart"
      summary: "Delete a cart item"
      description: "Delete a cart item"
      requestBody:
        $ref: '#/components/requestBodies/CartID_ProductID'
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/cart/{cart_id}:
    get:
      tags: 
        - "cart"
      summary: "Get a cart by id"
      description: "Get a cart by cart id"
      parameters:
        - name: cart_id
          in: path
          required: true
          description: Id of cart to retrieve.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        $ref: '#/components/responses/200-204-400'
  /api/v1/cart/user/{user_id}:
    get:
      tags: 
        - "cart"
      summary: "Get carts by user id"
      description: "Get carts by user id"
      parameters:
        - name: user_id
          in: path
          required: true
          description: User id of carts to retrieve.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        $ref: '#/components/responses/200-204-400'
  /api/v1/login:
    get:
      tags: 
      - "login"
      summary: "Show default page"
      description: "Show login page"
      parameters: []
      responses:
        $ref: '#/components/responses/200-400'
    post:
      tags: 
      - "login"
      summary: "Login"
      description: "Log in a user with provided username/password and auth via passport"
      requestBody:
        $ref: '#/components/requestBodies/UserPassword'
      responses:
        $ref: '#/components/responses/200-400-401'
  /api/v1/order:
    get:
      tags: 
      - "order"
      summary: "Get orders"
      description: "Get all orders in the database"
      parameters: []
      responses:
        $ref: '#/components/responses/200-400'
    post:
      tags: 
      - "order"
      summary: "Create an order"
      description: "Create an order from a user's cart"
      requestBody:
        $ref: '#/components/requestBodies/Order'
      responses:
        $ref: '#/components/responses/200-400'
    delete:
      tags: 
      - "order"
      summary: "Delete order"
      description: "Delete an order by id"
      requestBody:
          $ref: '#/components/requestBodies/OrderID'
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/order/{order_id}:
    get:
      tags: 
      - "order"
      summary: "Get order by id"
      description: "Get an order by id"
      parameters:
        - name: order_id
          in: path
          required: true
          description: Id of order to retrieve.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/order/user/{user_id}:
    get:
      tags: 
        - "order"
      summary: "Get orders by user id"
      description: "Get orders by user id"
      parameters:
        - name: user_id
          in: path
          required: true
          description: User id of orders to retrieve.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        $ref: '#/components/responses/200-204-400'
  /api/v1/product:
    get:
      tags: 
      - "product"
      summary: "Get products"
      description: "Get all products in the database"
      parameters: []
      responses:
        $ref: '#/components/responses/200-400'
    post:
      tags: 
      - "product"
      summary: "Add a product"
      description: "Add a product to the database"
      requestBody:
        $ref: '#/components/requestBodies/Product'
      responses:
        $ref: '#/components/responses/201-400'
    put:
      tags: 
      - "product"
      summary: "Update"
      description: "Update a product's name / description / price"
      requestBody:
        $ref: '#/components/requestBodies/Product'
      responses:
        $ref: '#/components/responses/200-204-400'
    delete:
      tags: 
      - "product"
      summary: "Delete product"
      description: "Delete product from the database"
      requestBody:
          $ref: '#/components/requestBodies/ProductID'
      responses:
        $ref: '#/components/responses/204-400'
  /api/v1/product/{productID}:
    get:
      tags: 
      - "product"
      summary: "Get product"
      description: "Get a product by id"
      parameters:
        - name: productID
          in: path
          required: true
          description: Id of product to retrieve.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/product/search:
    post: 
      tags:
        - product
      summary: "Search products"
      description: "Search products name and description for a single search term"
      requestBody:
        required: true  
        content: 
          application/json:
            schema: 
              type: object
              properties:
                searchTerm:
                  type: string
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/product-category:
    get:
      tags: 
      - "product-category"
      summary: "Get product categories"
      description: "Get all product categories in the database"
      parameters: []
      responses:
        $ref: '#/components/responses/200-400'

  /api/v1/product-category/{category_id}:
    get:
      tags: 
      - "product-category"
      summary: "Get product category"
      description: "Get product category by id"
      parameters:
        - name: category_id
          in: path
          required: true
          description: Id of product category to retrieve.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/register:
    get:
      tags: 
      - "register"
      summary: "Get"
      description: "Displays register form page"
      responses:
        $ref: '#/components/responses/200-400'
    post:
      tags: 
      - "register"
      summary: "Add user"
      description: "Adds user to database"
      requestBody:
        $ref: '#/components/requestBodies/UserEmailPassword'
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/user:
    get:
      tags: 
      - "user"
      summary: "Get all users"
      description: "Get all users from the database"
      parameters: []
      responses:
        $ref: '#/components/responses/200-204-400'
    post:
      tags: 
      - "user"
      summary: "Create a user"
      description: "Add a user record to the database"
      requestBody:
        $ref: '#/components/requestBodies/UserEmailPassword'
      responses:
        $ref: '#/components/responses/201-400'
    put:
      tags: 
      - "user"
      summary: "Update a user"
      description: "Update a user record in the database"
      requestBody:
        $ref: '#/components/requestBodies/UserIdEmailPassword'
      responses:
        $ref: '#/components/responses/200-204-400'
    delete:
      tags: 
      - "user"
      summary: "Delete a user"
      description: "Delete a user record from the database"
      requestBody:
        $ref: '#/components/requestBodies/UserID'
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/user/{userID}:
    get:
      tags: 
      - "user"
      summary: "Get a user"
      description: "Get a user record from the database"
      parameters:
      - name: userID
        in: path
        required: true
        description: Id of user to retrieve.
        schema:
          type : integer
          format: int64
          minimum: 1
      responses:
        $ref: '#/components/responses/200-400'

  /api/v1/address:
    get:  
      tags: 
        - "address"
      summary: "Get all address records"
      description: "Get all address records from the database"
      parameters: []
      responses:
        $ref: '#/components/responses/200-400'
    post: 
      tags: 
        - "address"
      summary: "Create address"
      description: "Add address record to the database"
      requestBody:
        $ref: '#/components/requestBodies/CreateAddress'
  /api/v1/address/{addressId}:
    get:  
      tags: 
        - "address"
      summary: "Get address record by address id"
      description: "Get one address record from the database"
      parameters: 
      - name: addressId
        in: path
        required: true
        description: Id of address to retrieve.
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/address/user/{userId}:
    get:  
      tags: 
        - "address"
      summary: "Get address records by user id"
      description: "Get all address records for a user from the database"
      parameters: 
      - name: userId
        in: path
        required: true
        description: User id for all address records to retrieve.
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        $ref: '#/components/responses/200-400'

  /api/v1/payment:
    get:
      tags:
        - "payment"
      summary: "Get all payment records."
      description: "Get all payment records. Sensitive data is encrypted."
      parameters: []
      responses:
        $ref: '#/components/responses/200-400'
  /api/v1/payment/{paymentId}:
    get:  
      tags: 
        - "payment"
      summary: "Get payment info"
      description: "Get payment info by payment info id"
      parameters:
        - name: paymentId
          in: path
          description: "Id of payment info to retrieve."
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        $ref: '#/components/responses/200-400'
    /api/v1/payment/user/{userId}:
      get:  
        tags: 
          - "payment"
        summary: "Get payment info"
        description: "Get payment info by user id"
        parameters:
          - name: userId
            in: path
            description: "User id of payment info to retrieve."
            schema:
              type: integer
              format: int64
              minimum: 1
        responses:
          $ref: '#/components/responses/200-400'
  /api/v1/payment/stripe/charge:
    post:  
      tags: 
        - "payment"
      summary: "Make payment using Stripe API"
      description: "Make payment using Stripe API. We can't 'Try it out' here because we have no token to pass as source. Included here for completeness."
      requestBody:
        $ref: '#/components/requestBodies/Stripe'
      responses:
        $ref: '#/components/responses/200-500'
components:
  responses:
    200-400:
      description: Success / Bad request responses
      200: 
        description: 200 Success
      400: 
        description: 400 Bad request
    200-204-400:
      description: Success / No content / Bad request responses
      200: 
        description: 200 Success
      204: 
        description: 204 No Content
      400: 
        description: 400 Bad request
    200-400-401:
      description: Success / Not Authorized / Bad request responses
      200: 
        description: 200 Success
      400: 
        description: 400 Bad request
      401: 
        description: 401 Not Authorized
    201-400:
      description: Created / Bad request responses
      201: 
        description: 201 Created
      400: 
        description: 400 Bad request
    204-400:
      description: No Content / Bad request responses
      204: 
        description: 204 No Content
      400: 
        description: 400 Bad request
    200-500:
      description: No Content / Bad request responses
      200: 
        description: 200 Success
      500: 
        description: 500 Server Failure
  requestBodies:
    Stripe: 
        description: "Process payment request using Stripe API"
        required: true
        content:
          application/json:
            schema: 
              type: object  
              properties:
                amount: 
                  type: number
                source:
                  type: string
                receipt_email:
                  type: string
    Payment: 
        description: "Form data for a new payment record"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                nameOnCard:
                  type: string
                paymentTypeId:
                  type: integer
                cardNumber:
                  type: string
                expDate:
                  type: string
                orderAmount:
                  type: number
    CreateAddress:
        description: "Form data for a new address record"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                userId: 
                  type: integer
                firstName:
                  type: string
                lastNane:
                  type: string
                address1:
                  type: string
                address2:
                  type: string
                city:
                  type: string
                stateProvince:
                  type: string
                postalCode:
                  type: string
                country:
                  type: string
    CartID_ProductID:
        description: Form data for item to delete from a cart
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                cart_id:
                    type: integer
                product_id:
                    type: integer
    CartItem:
        description: A product / item that goes into a cart
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                cart_id:
                    type: integer
                product_id:
                    type: integer
                product_quantity:
                    type: integer
                product_price:
                    type: number
    Order: 
        description: Create an order from a user's cart
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user_id:  
                  type: integer
                cart_id:  
                  type: integer
    OrderID:
        description: ID of an order
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                order_id:
                    type: integer
    Product:
        description: Something for sale
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                    type: integer
                name:
                    type: string
                description:
                    type: string
                price:
                    type: number 
                image_url:
                    type: string
    ProductID: 
        description: ID of a product
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                product_id:
                      type: integer
    UserID: 
        description: ID of a user
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                  user_id:
                    type: integer
    UserIdEmailPassword:
        description: Username / user id / Email / password
        required: true
        content:
          application/x-www-form-urlencoded:
            schema: 
              type: object
              properties:
                user_id:
                  type: integer
                username:
                  type: string
                email:
                  type: string
                password: 
                  type: string
    UserEmailPassword:
        description: Username / Email / Password
        required: true
        content:
          application/x-www-form-urlencoded:
            schema: 
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password: 
                  type: string
