-- Database: codecademy_ecommerce_rest_api_v2

-- psql postgres -d codecademy_ecommerce_rest_api_v2 -f -a ./db/createDatabase.sql


DROP DATABASE IF EXISTS codecademy_ecommerce_rest_api_v2;

CREATE DATABASE codecademy_ecommerce_rest_api_v2
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE codecademy_ecommerce_rest_api_v2
    IS 'database for the ecom / rest project';

-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

BEGIN;

CREATE TABLE IF NOT EXISTS public."Order_Item"
(
    id integer NOT NULL,
    order_id integer,
    product_id integer,
    line_item_price money,
    product_quantity integer
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    id integer NOT NULL,
    user_id integer,
    total_price money,
    CONSTRAINT "Orders_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Products"
(
    id integer NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    price money,
    CONSTRAINT "Products_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    id integer NOT NULL,
    user_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Users_pkey" PRIMARY KEY (id)
);

COMMENT ON TABLE public."Users"
    IS 'users / customers';

ALTER TABLE IF EXISTS public."Order_Item"
    ADD CONSTRAINT order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public."Orders" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order_Item"
    ADD CONSTRAINT product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public."Products" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders"
    ADD CONSTRAINT user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;